// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// TransfersPublisherMock is an autogenerated mock type for the TransfersPublisher type
type TransfersPublisherMock struct {
	mock.Mock
}

type TransfersPublisherMock_Expecter struct {
	mock *mock.Mock
}

func (_m *TransfersPublisherMock) EXPECT() *TransfersPublisherMock_Expecter {
	return &TransfersPublisherMock_Expecter{mock: &_m.Mock}
}

// Publish provides a mock function with given fields: operation, transferID
func (_m *TransfersPublisherMock) Publish(operation string, transferID string) error {
	ret := _m.Called(operation, transferID)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(operation, transferID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TransfersPublisherMock_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type TransfersPublisherMock_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - operation string
//   - transferID string
func (_e *TransfersPublisherMock_Expecter) Publish(operation interface{}, transferID interface{}) *TransfersPublisherMock_Publish_Call {
	return &TransfersPublisherMock_Publish_Call{Call: _e.mock.On("Publish", operation, transferID)}
}

func (_c *TransfersPublisherMock_Publish_Call) Run(run func(operation string, transferID string)) *TransfersPublisherMock_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *TransfersPublisherMock_Publish_Call) Return(_a0 error) *TransfersPublisherMock_Publish_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TransfersPublisherMock_Publish_Call) RunAndReturn(run func(string, string) error) *TransfersPublisherMock_Publish_Call {
	_c.Call.Return(run)
	return _c
}

// NewTransfersPublisherMock creates a new instance of TransfersPublisherMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransfersPublisherMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *TransfersPublisherMock {
	mock := &TransfersPublisherMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
